### PR TITLE
Add optional dockerFile option to the DockerBuildImage task.

### PR DESCRIPTION
**Pull request by llamahunter**
Separate the build context from the Dockerfile location.
Update version of docker-java to 1.1.0

### CODE REVIEW

**Comment by llamahunter** [comment]
Ok... think this works now.  Still unable to run the integration test, tho.  But I did test that I was able to set the dockerFile in my own gradle scripts.  Unfortunately, 'docker' itself doesn't allow setting a Dockerfile outside of the build context, but at least now it is possible to set it to a file named anything anywhere within the context.

**Comment by bmuschko** [comment]
What's the reason you cannot run the integration tests?

**Comment by llamahunter** [comment]
Ah.. did not scroll all the way to the bottom of the readme, it seems.  I'll give that a try.  I'm running boot2docker, for which I haven't yet figured out how to make non TLS.

**Comment by bmuschko** [comment]
I added this today so you couldn't have seen this earlier. With that you should be able to use TLS as well.

BTW: In case you want to disable TLS, [the documentation](https://github.com/bmuschko/gradle-docker-plugin#working-with-a-docker-instance-without-tls) shows how to do it.

**Comment by bmuschko** [comment]
I just released a new version of the plugin that uses the latest Docker Java version. Please rebase your pull request.

**Comment by llamahunter** [comment]
Horray... integration tests passed.

**Comment by llamahunter** [comment]
rebased (I think).  integration tests still seem to be passing.

**Comment by bmuschko** [comment]
Thanks for the pull request. I think I want to solve this slightly differently by just having a single property `File dockerFile`. I am going to make the relevant changes and will let you know when this goes out.

**Comment by llamahunter** [comment]
No problem.  I have a local build in my own maven repo.  Look forward to your solution!  To make it *really* work the way I think it should, however (arbitrary location of Dockerfile completely separate and outside the build context) will likely require a change in the way docker-java creates its staged InputStream in Dockerfile.ScannedResult.buildDockerFolderTar().

**Comment by llamahunter** [comment]
Hmm... but if you get rid of inputDir, aren't you just going to continue with conflating the root of the build context with the location of the Dockerfile?

**Comment by bmuschko** [comment]
I had actually thought about a different problem you were trying to solve - allowing the use of other files than the standard convention as Dockerfiles. This makes more sense now. I am going to have a look at this again soon.

**Comment by llamahunter** [comment]
Well, that too.  Actually, looking at the current code in docker-Java, I think people could pass the path to the "otherly named" Dockerfile file as inputDir (instead of a directory), and it would do the right thing.

**Comment by bmuschko** [comment]
That was how I wanted to implement it before I noticed that you had a different requirements. Generally speaking, allowing a parameter to be different things is a bad practice IMHO. But that's something the Docker Java library has to deal with and this plugin can hide.

**Comment by llamahunter** [comment]
Wasn't a fan of the docker-java approach either. Thus why I added a new parameter.

**Comment by llamahunter** [comment]
Rebased to HEAD. Any chance this will get pulled someday?

**Comment by bmuschko** [comment]
Sorry for the delay. I'll have to review this again soon.

**Comment by bmuschko** [comment]
Thanks for the pull request. It has been merged. I need to reshuffle the tests a bit. For now I remove it.

**Pull request merged**
