### PR TITLE
Replace usage of deprecated DefaultTask.newOutputFile method

### LINKED ISSUE #831: Deprecation warning for DefaultTask.newOutputFile() in Gradle 5.4.1
Gradle 5.4.1 logs a deprecation warning when using the `docker-remote-api` plugin in version `4.10.0`:

```
The DefaultTask.newOutputFile() method has been deprecated. This is scheduled to be removed in Gradle 6.0. Please use the ObjectFactory.fileProperty() method instead.
        at org.gradle.api.DefaultTask.newOutputFile(DefaultTask.java:53)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.bmuschko.gradle.docker.tasks.image.DockerBuildImage.<init>(DockerBuildImage.groovy:176)
        at com.bmuschko.gradle.docker.tasks.image.DockerBuildImage_Decorated.<init>(Unknown Source)
        […]
```

### PR DESCRIPTION
**Pull request by hugares**
Resolves #831

### CODE REVIEW

**Comment by bmuschko** [comment]
The change fails one of the integration tests: https://scans.gradle.com/s/3mm6uhgyvd5vq/tests/bz7j4uv5n63ns-i7dc5kuczz2ci. Can you have another look and make the relevant change in the test?

**Comment by hugares** [comment]
It passed the integration tests but I got a failure in the functional tests this time:

```
com.bmuschko.gradle.docker.tasks.container.DockerCreateContainerFunctionalTest > with autoRemove set, the container is removed after stopping FAILED
    org.spockframework.runtime.ConditionFailedWithExceptionError at DockerCreateContainerFunctionalTest.groovy:170
        Caused by: java.lang.NullPointerException at DockerCreateContainerFunctionalTest.groovy:170
```

**Comment by cdancy** [comment]
Do things fail locally or only in CI?

**Comment by hugares** [comment]
I cannot run successfully all the functional tests locally, I have an old version of docker(thanks to redhat/fedora) which causes some tests to fail. I will setup a VM with a recent version of docker soon to be able to run all the tests locally.

It looks like this PR is good to go now, last 2 CI runs before successful one failed because of flaky tests.

**Comment by bmuschko** [comment]
I think it's the same reason as https://github.com/bmuschko/gradle-docker-plugin/pull/826 so once that's merged the tests should pass consistently.

**Comment by bmuschko** [comment]
@cdancy This issue is currently assigned to you. Were you planning to merge soon?

**Comment by hugares** [comment]
Can we get this one in?

**Comment by cdancy** [comment]
Yeah we can merge it in. I've been traveling the past couple weeks and plan to do more so haven't been as attentive.

**Pull request merged**
