### PR TITLE
Introduce platform parameter for build image task

### PR DESCRIPTION
**Pull request by bmuschko**

### CODE REVIEW

**Comment by RicardoMonteiroSimoes** [comment]
@bmuschko as noted above, there appears to be 0 indication of where/how to use the new platform property.

**Comment by bmuschko** [comment]
@RicardoMonteiroSimoes It's here: https://bmuschko.github.io/gradle-docker-plugin/current/api/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.html#platform

**Comment by veda-s4dhak** [comment]
@bmuschko is there a way to specify the platform label in the build.gradle. Read the link you provided but its unclear if the indented way to specify platform is in the build.gradle or another way. 

docker {
	springBootApplication {
		// within here?
	}
}

**Comment by bmuschko** [comment]
@veda-s4dhak You would define the platform in the build script but not with the help of the plugin's extension. You need to set the property for the task of type `DockerBuildImage`.

```
dockerBuildImage.platform = 'linux/s390x'
```

**Pull request merged**
