### PR TITLE
Attempting v5.3.0 release from this branch

### PR DESCRIPTION
**Pull request by cdancy**
!!! DO NOT MERGE !!!

### CODE REVIEW

**Comment by cdancy** [comment]
@bmuschko just creating PR to see what things will look like before I attempt a release. 

DO NOT MERGE THIS!!!

**Comment by cdancy** [comment]
`v5.3.0` has been released!

**Comment by cdancy** [comment]
At least we now know that should we need to do a patch release it should be simple enough.

**Comment by bmuschko** [comment]
Cool

**Pull request closed without merging**
