### PR TITLE
ISSUE-81: expose support for LogDriver

### PR DESCRIPTION
**Pull request by cdancy**
PR address #81 . @bmuschko take a look at the implementation and tell me what you think. I went the closure route, and subsequently needing that closure to return 2 values (1 for logtype and 1 for optional-parameters), as I didn't see any other sensible way of exposing this functionality whilst still keeping the client/caller code sane.

### CODE REVIEW

**Comment by cdancy** [comment]
Hung here for me every other time or so I ran tests. Not sure what that's about but they did succeed when they did go through.

**Comment by cdancy** [comment]
@bmuschko any thoughts here?

**Comment by bmuschko** [comment]
We should represent `LogConfig` as a class here instead of a `Closure`. That will make it more clear to consumers on what to pass in here. The instance should be annotated with `@Nested` in `DockerCreateContainer`.

    class LogConfig {
        @Input String type
        @Input Map<String, String> config = [:]
    }

Could you please touch up the pull request?

**Comment by cdancy** [comment]
@bmuschko just got back to this now. It hadn't even occured to me to use another class for LogConfig as I've never seen class instantiation on a task parameter. I took your example above and put it as an inner class to DockerCreateContainer as that's the only place it can be used anyway. Fixed another line or 2 to get things working. All tests passed as expected.

**Comment by bmuschko** [comment]
Thanks for the pull request. It has been merged.

**Pull request merged**
