### PR TITLE
Revert shading of Docker Java

### PR DESCRIPTION
**Pull request by bmuschko**
Fix for https://github.com/bmuschko/gradle-docker-plugin/issues/1147.

### CODE REVIEW

**Comment by Sineaggi** [comment]
Should the dependency also be excluded from repackaging?

**Comment by bmuschko** [comment]
I tried. It seemed to cause other issues. Looks like shading Docker Java won't work. I reverted those changes here. Can you try with this?

**Comment by Sineaggi** [comment]
I'd simply much prefer not shading at all. Relocation has problems with jna (jni) and not shading has problems with two versions of the same jar being available on the classpath.

**Comment by bmuschko** [comment]
@Sineaggi Yeah, that's unfortunate. Long term, Gradle core should run each plugin in separate classloader to ensure that dependencies don't conflict with each other. At this time, there's nothing else we could have tried from my perspective than shading.

> It’s important to understand that a Gradle plugin does not run in its own, isolated classloader. In turn those dependencies might conflict with other versions of the same library being resolved from other plugins and might lead to unexpected runtime behavior. When writing Gradle plugins consider if you really need a specific library or if you could just implement a simple method yourself. A future version of Gradle will introduce proper classpath isolation for plugins.

https://docs.gradle.org/current/userguide/designing_gradle_plugins.html

**Comment by big-andy-coates** [comment]
I've tested this locally on my M1 Mac and images built perfectly 👍

**Comment by Sineaggi** [comment]
@bmuschko Long term I agree, but I honestly think that for now just having no shading has the least amount of problems.

**Pull request merged**
