### PR TITLE
If NPE thrown trying to access state.health.status than catch NPE and…

### PR DESCRIPTION
**Pull request by cdancy**
… attempt to access state.status

Addresses #518

### CODE REVIEW

**Comment by cdancy** [comment]
@orzeh can you please take a look at how I refactored the logic a bit here to see if makes sense to you and if there is anything I'm missing? The idea is that if the `Health` object is null, and thus not present, then we fall back to just using the generic status of the container.

**Comment by cdancy** [comment]
@bmuschko agreed however we already have loads of tests around this area, one that looks exactly like your snippet above, and I'm still scratching my head as to why when the tests run this `Health` object is present and yet when I do a `docker inspect <container-name>` on my system I don't see it. Have to do a bit more digging here as to what is going on. Maybe the `Health` object goes away after some point once the container is live and running? IDK.

**Comment by orzeh** [comment]
@cdancy I think `Health` object is only returned when [`HEALTHCHECK`](https://docs.docker.com/engine/reference/builder/#healthcheck) instruction is used. IMO the task `DockerWaitHealthyContainer` is supposed to be used with conjunction with it. If we don't receive health object it means something is not configured well and we should add log statement or/and break build. This probably requires dedicated functional test as it will document the expected behavior. WDYT?

**Comment by cdancy** [comment]
@orzeh agreed on the logging. Maybe then if `Health` is missing we just return true here or do you think it makes sense to use the implementation I put in place. I'm on the fence here and could go either way.

**Comment by orzeh** [comment]
@cdancy I would use your new implementation with logging.

**Comment by cdancy** [comment]
Sounds good. Thanks @orzeh !

**Pull request merged**
