### PR TITLE
New task for copying files from a container to a host.  Fixes #56

### LINKED ISSUE #56: Add support for DockerCPContainer to copy files out of a container
I have a need to copy files that are created within the container as part of a gradle build process.  Supporting the docker cp command would be useful via this API.

### PR DESCRIPTION
**Pull request by petehayes**
I wasn't successful in running the integration tests on my machine so I am not sure if the one I added will work.  Otherwise, this will support copying files out of a container and storing them into a tar file on the host with the option of gzip compression.

### CODE REVIEW

**Comment by bmuschko** [comment]
Thanks for the pull request. I'd like to ask you for some minor cleanup before I merge it:

* Would you mind converting tabs into spaces?
* Remove semicolons

**Comment by petehayes** [comment]
I pushed those changes.  Thanks.

**Comment by bmuschko** [comment]
Thanks. I merged the pull request.

Two comments:

- The provided integration test didn't work. It threw a `com.github.dockerjava.api.NotFoundException`. We should add a test to `DockerWorkflowIntegrationTest` that creates a new container first and tries to copy the file.
- The response of the task should be handled by an instance of `com.bmuschko.gradle.docker.response.ResponseHandler`. The appropriate code should be moved there.

Would you be interested in working on any of these items in a separate pull request? At the moment I am not even sure if the task works properly.

**Comment by petehayes** [comment]
I tried to get the integration tests running but I couldn't figure out what was needed to do so.  I did test the task manually though.  If I could get help on how to run the tests properly, then I would make the necessary changes.

**Comment by bmuschko** [comment]
I still have to address some issues with running the integration tests with against a TLS-enabled Docker instance (see issue #48). Feel free to help out with that as well. Generally, you can run the tests without TLS.

**Comment by petehayes** [comment]
OK. I'll try running them again.

**Pull request merged**
