### PR TITLE
Upgrading to gradle 4.3.1

### PR DESCRIPTION
**Pull request by The-Alchemist**

### CODE REVIEW

**Comment by cdancy** [comment]
@The-Alchemist care to fix the failures that popped with this upgrade?

**Comment by The-Alchemist** [comment]
@cdancy : Unfortunately, I can't fix the issues. :(  After I submitted this, I bumped into https://github.com/bmuschko/gradle-docker-plugin/issues/490  . But it's good knowing that the issue exists in gradle v4.3.1 too, not just v 4.2/v4.3.

**Comment by cdancy** [comment]
@The-Alchemist aaahhh forgot to follow back up on that and will do so now.

**Comment by cdancy** [comment]
@The-Alchemist l'll finish the work on this PR and apply the changes noted [here](https://github.com/bmuschko/gradle-docker-plugin/issues/490#issuecomment-348047956) to get things moving forward.

**Pull request merged**
