### PR TITLE
Fixes bug with private repository url which was not applied to DockerClient

### PR DESCRIPTION
**Pull request by Frisch12**

### CODE REVIEW

**Comment by orzeh** [comment]
@Frisch12 why this change is needed? Also there are some failing tests.

**Comment by cdancy** [comment]
@Frisch12 just curious: why the reason for closing?

**Comment by Frisch12** [comment]
Sorry. I was dumb as fuck. Thought there was a bug in this grade plugin. But I realized that I was just using it wrong. RegistryURL has no effect and is just a useless parameter for DockerPushImage tasks.

**Comment by cdancy** [comment]
@Frisch12 hahaha no worries ;)

**Pull request closed without merging**
