### PR TITLE
make runCommand closure'able

### PR DESCRIPTION
**Pull request by kuehl**
:+1:

### CODE REVIEW

**Comment by cdancy** [comment]
@kuehl we are actually attempting to address this issue, though for every task, with PR #153. The idea is much the same: allow users, via a closure, to handle the execution of the command at hand.

**Comment by bmuschko** [comment]
@cdancy The use case @kuehl provides here is a different one. It's for defining a Dockerfile command with the help of a closure.

@kuehl Before we can merge the PR can you please add a test case in [DockerfileTest.groovy](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/test/groovy/com/bmuschko/gradle/docker/tasks/image/DockerfileTest.groovy)?

**Comment by cdancy** [comment]
@bmuschko you're right. The semantics used here were similar, and seeing as how other folks have been asking for my above named PR, I assumed this was related.

**Comment by kuehl** [comment]
changes commited: anything missing?

**Comment by bmuschko** [comment]
@kuehl Thanks, LGTM.

**Comment by cdancy** [comment]
Merged. Thanks again @kuehl

**Comment by bmuschko** [comment]
@cdancy Can you please add the released version as milestone to all PRs that were merged and mention them in the release notes?

**Comment by cdancy** [comment]
@bmuschko done and done ;)

**Pull request merged**
