### PR TITLE
ISSUE-798 Print whole lines by collecting output and waiting for newline

### LINKED ISSUE #798: DockerBuildImage output is mangled
### Expected Behavior
The output is printed as it is printed by the `docker build` command.

### Current Behavior
The output contains too many newlines and more advanced output (with ascii escape codes, such as curl) are totally mangled. For example, output when using curl:
```
[91m+ curl -fSL https://apache.belnet.be/hadoop/common/hadoop-2.9.1/hadoop-2.9.1.tar.gz -o hadoop.tar.gz

[91m  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  344M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[91m
[91m 
[91m 
[91m0
[91m 
[91m  0:00:
...
[91m04 
[91m 0:01
[91m:33 361
[91m8k
  5  344M    5 18.0M    0     0  3587k      0  0:01:38  0:00:05  0:01:33 3702k
...
```

### Context
This problem is most noticeable when executing `curl` in the Dockerfile.

### Steps to Reproduce (for bugs)
Build any Dockerfile with the Gradle plugin.

### Cause

I did some debugging and the cause is here: https://github.com/bmuschko/gradle-docker-plugin/blob/3d775c1380c29e84873ae347ca5c6fac3812b92b/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy#L220

The response stream in the call back does not always correspond with a full line; sometimes the lines are split, even into individual characters. However, Gradle's `logger.quiet()` function seems to automatically add newlines. The `trim()` function, which is currently used (was added in https://github.com/bmuschko/gradle-docker-plugin/pull/206), also seems to trim some tokens from the ascii escape codes, resulting in those being printed instead of used.

I have a local patch, were I store the streams into a `StringBuffer` until a newline is encountered. This fixes the most annoying problems (newlines work properly, lines are no longer split and some ascii escape codes, such as colours, work). Not everything is fixed: for example, the ascii escape code to go to the beginning of the line does not work. When using this patch, the output from above would be:
```
+ curl -fSL https://apache.belnet.be/hadoop/common/hadoop-2.9.1/hadoop-2.9.1.tar.gz -o hadoop.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  344M    0  112k    0     0    98k      0  0:59:38  0:00:01  0:59:37   98k
  1  344M    1 4560k    0     0  2141k      0  0:02:44  0:00:02  0:02:42 2140k
  2  344M    2  9.7M    0     0  3182k      0  0:01:50  0:00:03  0:01:47 3182k
  4  344M    4 15.0M    0     0  3716k      0  0:01:34  0:00:04  0:01:30 3716k
  5  344M    5 20.4M    0     0  4083k      0  0:01:26  0:00:05  0:01:21 4208k
  7  344M    7 25.8M    0     0  4325k      0  0:01:21  0:00:06  0:01:15 5286k
  9  344M    9 31.4M    0     0  4509k      0  0:01:18  0:00:07  0:01:11 5516k
 10  344M   10 36.6M    0     0  4612k      0  0:01:16  0:00:08  0:01:08 5511k
 12  344M   12 42.0M    0     0  4718k      0  0:01:14  0:00:09  0:01:05 5546k
 13  344M   13 47.4M    0     0  4795k      0  0:01:13  0:00:10  0:01:03 5524k
 15  344M   15 52.7M    0     0  4853k      0  0:01:12  0:00:11  0:01:01 5499k
...
```
If this seems acceptable, I am willing to make a PR.

### Your Environment
Windows 10 Home, using Docker Toolbox
```bash
> docker --version
Docker version 18.09.3, build 774a1f4eee
```
Perhaps this is a Windows issue, but I don't have access to Linux at the moment, so I don't know.

### PR DESCRIPTION
**Pull request by niknetniko**
Closes #798.

### CODE REVIEW

**Comment by bmuschko** [comment]
Thanks for providing the pull request. I am wondering if the logic should apply to other callbacks as well. If it does then we should break out reusable logic and apply it to other operations.

**Comment by niknetniko** [comment]
That's possible, but when I did a search for similar situations I only found this: https://github.com/bmuschko/gradle-docker-plugin/blob/d1ed5cd613cab8bcbf1c6a029bae20c1fb1ba47a/src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerLogsContainer.groovy#L167

As I wasn't entirely sure what that code does, I left it alone. It is very possible I missed some code.

**Comment by niknetniko** [comment]
I have extracted the logic for collecting strings into a utility class and also added some basic tests for that utility class.

**Comment by niknetniko** [comment]
My apologies, seems I forgot to close the output collector, meaning sometimes not all output is actually printed.

**Comment by cdancy** [comment]
Taking this in. Thanks for the fix @niknetniko !!!

**Pull request merged**
