### PR TITLE
Fix issue #128 DockerCreateContainer.exposedPorts should not be a Map

### PR DESCRIPTION
**Pull request by Nekitos**
I think map it's a best representation of exposed ports. Simply:
```groovy
exposedPorts=[
   'tcp': [t_p1, t_p2, t_p3],
  'udp': [u_p1, u_p2, u_p3]
]
```

### CODE REVIEW

**Comment by bmuschko** [comment]
Please see the proposed solution in issue #128. We want to represent exposed ports in a different way. Could you please make the change to your PR?

**Comment by Nekitos** [comment]
Ok, I'll do it.

**Comment by Nekitos** [comment]
Think now it looks like in your conversation in issue #128

**Comment by cdancy** [comment]
+1 lgtm. @bmuschko if no objections I can merge.

**Comment by cdancy** [comment]
@Nekitos would you mind doing a squash then I can merge this PR?

**Comment by Nekitos** [comment]
what do you mean when you telling 'squash'? I'm Russian. So, may be I don't understand your terminology. :-)

**Comment by cdancy** [comment]
@Nekitos it's to combine all of your commits into a single commit making the history a bit easier to read and manage. Here is a good tutorial:

https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by Nekitos** [comment]
Sorry, @cdancy. Some issues were with squashing. Think because I made mistakes on last commits, and 'git rebase' is not works correctly. Anyway I dropped previous commits. Then I rolled my branch to begin stage and then I apply patch

**Comment by Nekitos** [comment]
Sorry for this, guys. Think I need more experience with git

**Comment by cdancy** [comment]
@Nekitos no worries and thanks for the PR!

**Comment by bmuschko** [comment]
I would have liked to see an integration test as well just to make sure it actually works.

@cdancy Can you please also mention this functionality to the [release notes](https://github.com/bmuschko/gradle-docker-plugin/blob/master/RELEASE_NOTES.md)?

**Comment by cdancy** [comment]
I can add a test and update the release notes.

**Comment by bmuschko** [comment]
@cdancy Great, thanks!

**Pull request merged**
