### PR TITLE
Rename timeout properties to waitTime so as not to clobber the exiting timeout property on gradles Task.

### PR DESCRIPTION
**Pull request by cdancy**
More fallout from: https://docs.gradle.org/5.0/userguide/more_about_tasks.html#sec:task_timeouts

### CODE REVIEW

**Comment by cdancy** [comment]
@bmuschko looks like you knocked out some of the fallout a few releases ago just missed these.

**Comment by bmuschko** [comment]
@cdancy Looks like you change broke the build: https://scans.gradle.com/s/4cb7gtdv24uc4/tests/dqwcqqtprpdqc-sbol5sl7njrcg. Can you please fix?

**Comment by cdancy** [comment]
@bmuschko hmmm ... I did see that but re-kicked things again and was able to do a release. Let me look at things as this, like all things, wasn't failing locally :)

**Comment by bmuschko** [comment]
@cdancy Any idea when you'll be able to look at it? Have a PR waiting and I don't want to it fail on CI.

**Comment by cdancy** [comment]
@bmuschko I _think_ it should be good to go?!? I was able to re-run the job and it passed as expected. The task itself catches the noted exception and swallows it so in theory things should be fine.

**Comment by bmuschko** [comment]
@cdancy The test probably became flaky or there's some sort of timing issue. I will let you know if it happens again.

**Comment by cdancy** [comment]
Sounds good. I was thinking maybe it hit a commit that I over wrote. IDK.

**Pull request merged**
