### PR TITLE
Handle missing ServerURL from auth helper response

### LINKED ISSUE #955: Looking up registry auth logs NPE and stacktrace, but still succeeds
I use this plugin to build and push images to Google Container Registry. This involves using `gcloud` as a Docker credential helper, which is correctly identified and used by the plugin to successfully push images.

However, when collecting registry auth information, the helper does not return a `ServerURL` value (possibly because the registry name is sufficient?). When this `AuthConfig` (without a `ServerURL`) is passed to `docker-java`'s `AuthConfigurations#addConfig(AuthConfig)`, it results in an NPE because this method tries to insert the `AuthConfig` into a `TreeMap` using the (`null`) `ServerURL` as the key.

This _might_ be considered a bug in `docker-java`, but it's possible that the `AuthConfigurations` code expects all `AuthConfig`s it is passed to have a non-null `ServerURL`, so maybe this plugin should ignore credential helper responses that lack one.

### Expected Behavior

Building an image while the `gcloud` Docker credential helper is enabled should succeed without error.

### Current Behavior

Building an image while the `gcloud` Docker credential helper is enabled prints an NPE and stacktrace, while still succeeding.

### Context

- Where the NPE originates in this plugin: [`RegistryAuthLocator.groovy:196`](https://github.com/bmuschko/gradle-docker-plugin/blob/v6.6.0/src/main/groovy/com/bmuschko/gradle/docker/internal/RegistryAuthLocator.groovy#L196)
- Where this plugin invokes the Docker credential helper and parses the result, with a `null` `ServerURL`: [`RegistryAuthLocator.groovy:338`](https://github.com/bmuschko/gradle-docker-plugin/blob/v6.6.0/src/main/groovy/com/bmuschko/gradle/docker/internal/RegistryAuthLocator.groovy#L338-L355)
- Code in `docker-java` where the NPE is produced: [`AuthConfigurations.java:16`](https://github.com/docker-java/docker-java/blob/3.2.5/docker-java-api/src/main/java/com/github/dockerjava/api/model/AuthConfigurations.java#L16)

### Steps to Reproduce (for bugs)

- Create a GCP project and enable GCR (not sure if this is actually necessary; maybe the credential can be set up to reproduce this issue without having access to an actual GCR registry)
- Run `gcloud auth configure-docker` to set up the Docker credential helper
- Build an image using this plugin

Example output:

```
Failure when attempting to lookup auth config (configFile: /home/.../.docker/config.json). Falling back to docker-java default behaviour
java.lang.NullPointerException
        at java.base/java.util.TreeMap.put(TreeMap.java:561)
        at com.github.dockerjava.api.model.AuthConfigurations.addConfig(AuthConfigurations.java:16)
        at com.bmuschko.gradle.docker.internal.RegistryAuthLocator.lookupAllAuthConfigs(RegistryAuthLocator.groovy:196)
        at com.bmuschko.gradle.docker.internal.RegistryAuthLocator.lookupAllAuthConfigs(RegistryAuthLocator.groovy:228)
        at com.bmuschko.gradle.docker.internal.RegistryAuthLocator.lookupAllAuthConfigs(RegistryAuthLocator.groovy:217)
        at com.bmuschko.gradle.docker.tasks.image.DockerBuildImage.runRemoteCommand(DockerBuildImage.groovy:278)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.start(AbstractDockerRemoteApiTask.groovy:74)
        ...
```

And from the debug log:

```
2020-07-27T11:38:33.257+0200 [DEBUG] [com.bmuschko.gradle.docker.internal.RegistryAuthLocator] Executing docker credential helper: docker-credential-gcloud to locate auth config for: eu.gcr.io
2020-07-27T11:38:33.685+0200 [DEBUG] [com.bmuschko.gradle.docker.internal.RegistryAuthLocator] Credential helper response: {
  "Secret": "<secret>",
  "Username": "_dcgcloud_token"
}
```

The Docker image build then begins and completes successfully.

### Your Environment

- Affects at least versions 6.5.0 and 6.6.0 of this plugin (latest as of this writing)
- Using `springBootApplication`, but shouldn't be relevant for this issue

### PR DESCRIPTION
**Pull request by patricklucas**
Closes #955

I didn't add a test because there are currently no tests that cover this method, probably because it actually an external command. I think it would need a bit of restructuring to allow for a mocked command for testing.

### CODE REVIEW

**Comment by gildor** [comment]
Do you need help with this PR? The warning is pretty annoying when work with gcloud docker registry

**Comment by frossbeamish** [comment]
Would love to see this PR finished. I agree with @gildor.
>The warning is pretty annoying when work with gcloud docker registry

**Comment by bmuschko** [comment]
>Do you need help with this PR?

@gildor Who did you direct your question to? Were you asking @patricklucas or me?

**Comment by gildor** [comment]
Sorry, yeah, I asked PR author

**Comment by patricklucas** [comment]
@gildor / @frossbeamish my job situation changed a bit in the last few months so I didn't get a chance to revisit this, but I think I could put some time in this week.

**Comment by bmuschko** [comment]
Thanks for making the relevant changes.

**Pull request merged**
