### PR TITLE
Up to date not working

### PR DESCRIPTION
**Pull request by hnine999**
Please do not create a Pull Request without first creating an ISSUE.

Issue is #871

Any change needs to be discussed before proceeding.
Failure to do so may result in the rejection of the Pull Request.

Explain the **details** for making this change: What existing problem does the Pull Request solve? Why is this feature beneficial?

**On adding new code**

Any new code added must contain relevant functionalTest(s) exercising all possible paths the code may take.

**On CI testing (currently using travis)**

Code will not be reviewed until CI passes.

**On automtatic closing of ISSUES**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by cdancy** [comment]
I see you made changes to the gradle version itself. Is that required to reproduce this problem?

**Comment by bmuschko** [comment]
@cdancy I think the Gradle version was changed because of https://github.com/bmuschko/gradle-docker-plugin/issues/866. Plugin version 5.2.0 fixed the issue.

**Comment by hnine999** [comment]
I believe it is.
-- Harmon

**Comment by hnine999** [comment]
I downgraded gradle from 5.6.1 to 5.1.1, and upgraded gradle-docker-plugin
to 5.2.0 (latter is committed).

Still getting the test failure.

-- Harmon

**Comment by bmuschko** [comment]
I looked through this a bit. It's behaving as designed though it might not be obvious right away to end users. You are assigning the current project directory to be the Docker build context directory. Gradle will check the contents of the current project directory _and_ the contents of all of its subdirectories for up-to-date checking. That also includes the `.gradle` directory which likely contains the timestamp of the previous build. Consequently, the build will never be up-to-date.

You can identify that by running with `--info`.

```
Task ':buildTensorflow' is not up-to-date because:
  Input property 'inputDir' file /Users/bmuschko/dev/tmp/docker-up-to-date/.gradle/5.6/executionHistory/executionHistory.bin has changed.
  Input property 'inputDir' file /Users/bmuschko/dev/tmp/docker-up-to-date/.gradle/5.6/executionHistory/executionHistory.lock has changed.
  Input property 'inputDir' file /Users/bmuschko/dev/tmp/docker-up-to-date/.gradle/5.6/fileHashes/fileHashes.bin has changed.
```

I'd suggest you move your `Dockerfile` to some other directory and point `inputDir` to it. e.g. `docker/Dockerfile`.

**Comment by hnine999** [comment]
Putting the Dockerfile in a subdirectory fixed the problem.  Thanks :)

**Pull request closed without merging**
