### PR TITLE
Extracts host configuration for better maintainability

### PR DESCRIPTION
**Pull request by bmuschko**
For more context, see https://github.com/bmuschko/gradle-docker-plugin/issues/861.

### CODE REVIEW

**Comment by cdancy** [comment]
Hmmm ... IDK. I'm on the fence. At least in this PR it seems to be a lot of change for getting the exact same thing whilst also putting in yet another backwards breaking change.

**Comment by bmuschko** [comment]
We are targeting a major version change here so this is our chance to make things more maintainable. Yes, it means breaking the API as-is but with other benefits attached to it. IMHO this has not been addressed in the past and we need to pay a higher price now as we added more and more properties over time.

Generally speaking, it's not too hard to explain to users why the change needed to happen. In consuming build scripts, the change is straightforward: use the `hostConfig` property.

BTW: This change has already been merged so if you don't want to revert the change, we are already in the game. ;-)

**Comment by cdancy** [comment]
Oh you merged this into master ... that's a bummer as the next release has to be a major version bump. Which also means no minor/patch versions can go out. Was hoping to get the "netty config" stuff merged in as it's not anything near breaking but even if I do that we'd still have to bump to next major version and our pipeline is massive and would require lots of work to account for this change. That's a huge bummer. Will have to think on this...

**Comment by orzeh** [comment]
I guess we can create a HF branch and release minor/patch versions from there?

**Comment by cdancy** [comment]
@orzeh I suppose that could work. Let me worry about the "netty config" stuff first and get a PR out before I stress out over this :)

**Comment by bmuschko** [comment]
> Oh you merged this into master ... that's a bummer as the next release has to be a major version bump. Which also means no minor/patch versions can go out. Was hoping to get the "netty config" stuff merged in as it's not anything near breaking but even if I do that we'd still have to bump to next major version and our pipeline is massive and would require lots of work to account for this change. That's a huge bummer. Will have to think on this...

I am planning to release the next major version within the next week or two. So it's not something you'll have to wait on for long. Yes, there are some API changes but depending on what part of the plugin you are using, it won't be as much work.

**Comment by cdancy** [comment]
I wish I could explain the size and scope of our build pipeline. It's the biggest most massive thing I've ever seen. LOADS of stuff being built across teams across the globe which use this plugin to varying degrees.

Could a patch release work like what Orzeh suggested above from prior to this merge?

**Comment by jberglund-BSFT** [comment]
@bmuschko @cdancy  I'm not a groovy expert, but also had misgivings about the api breaking change.. would it be possible in groovy to flatten the hostConfig props ontop of the CreateContainerCmd, prefer the `hostConfig.nnn` props, and add a warning that the flattened ones will be removed in the next release?

**Comment by bmuschko** [comment]
> Could a patch release work like what Orzeh suggested above from prior to this merge?

Sure, that could work but you'd probably have to run the release steps manually and merge back into `master` afterward. But before you do so, please identify the actual issue first.

**Comment by jberglund-BSFT** [comment]
@bmuschko I noticed in the docker-java project, HostConfig is also used in the inspect container response, I wonder if it shouldn't eventually be extracted outside of the DockerCreateContainerCmd to better match the lower layer in order to re-use

**Comment by bmuschko** [comment]
@jberglund-BSFT Yes, it should be done across the board. But I'd need some help from my team mates. ;-) This isn't my full time job.

**Comment by cdancy** [comment]
Ours either! That's why big breaking changes like this are scary!
> I'm not a groovy expert, but also had misgivings about the api breaking change.. would it be possible in groovy to flatten the hostConfig props ontop of the CreateContainerCmd, prefer the hostConfig.nnn props, and add a warning that the flattened ones will be removed in the next release?

I'm honestly not sure but sounds like a reasonable idea.

**Pull request merged**
