### PR TITLE
ISSUE-539: Pass file path on DockerSaveImage instead of file

### LINKED ISSUE #539: DockerSaveImage needs a file to exist instead of creating it
DockerSaveImage expects a file to exist. Proper behavior would be creating the file.

### PR DESCRIPTION
**Pull request by aol-nnov**
fixes #539 
obsoletes #543

let's bring some pace :))

all credits go to @kalap92 I've just removed irrelevant changes.

### CODE REVIEW

**Comment by cdancy** [comment]
@aol-nnov planned on doing a release today. If you can get this working within the next 8 hours or so I'll make sure it's in the next release.

**Comment by aol-nnov** [comment]
woah, red... I'll try to look into it, @cdancy

**Comment by aol-nnov** [comment]
@cdancy I don't get it!..
It keeps failing, but it was passing just fine in #543 !

What I've done so far is reverting `DockerLoadImage` stuff and rebasing this PR on the tip of master.

**Comment by cdancy** [comment]
@aol-nnov did you try running things locally to see if it's reproducible? It's entirely possible, though not likely, it's a travis-ci/infra issue.

**Comment by aol-nnov** [comment]
silly me! running locally now. will report back shortly :)

**Comment by kalap92** [comment]
Changes to loadDockerImage are necessary . Previously a file in the test wa created . I have changed that functionality. In the same test there is loadDockerImage task which in configuration phase expects the file to exist . That is why test are failing

**Comment by cdancy** [comment]
@kalap92 that makes sense. Maybe wrap that property set within a `doFirst{}` block to get around this issue?

**Comment by aol-nnov** [comment]
@cdancy I have the following with doFirst:
```
No value has been specified for property 'imageStream'.
```
weird

**Comment by cdancy** [comment]
@aol-nnov yeah gave that a try as well and got the same. I would be OK with you changing the `DockerLoadImage` task and change inputStream to `Closure<InputStream> inputStream` and then devs can write their tasks like: `imageStream = { new File("${savedImagePath}").newInputStream() }`

**Comment by aol-nnov** [comment]
@cdancy yeah, closure did the trick. pushing shortly.

not sure if I did everything right, though. lol

**Comment by cdancy** [comment]
This should do it. Once Travis-CI passed I'll merge. Thanks @aol-nnov

**Pull request merged**
