### PR TITLE
Issue #334: Configure Codenarc

### PR DESCRIPTION
**Pull request by MEZk**
#334 

1. Configured Codenarc with default ruleset.
2. Codenarc reports a huge amount of violations. See [Report](http://mezk.github.io/i334-codenarc-report/main.html). I propose to start applying fixes for violations package by package. Lets start for example from utils package. If you agree I change the sourceSets property of the plugin to validate only utils package and fix the violations. In the next PRs I will add one more package into validation and go on. We can find some of Codenarc rules controversial and we may exclude them later.

### CODE REVIEW

**Comment by MEZk** [comment]
@orzeh @cdancy 
Please, review and share your view on the proposed plan (see previous commit).

**Comment by cdancy** [comment]
@MEZk agree. I assumed massive amounts of violations for any of the proposed tools and so doing things on a package by package basis makes sense.

**Comment by orzeh** [comment]
@MEZk @cdancy yeah, sounds reasonable. 👍

**Comment by cdancy** [comment]
And ... If you're interested in kubernetes at all we've started development on the `gradle-kubernetes-plugin` which we could also benefit greatly from having these tools.

**Comment by MEZk** [comment]
1. Apply Codenarc rules for utils package
2. Disable Codenarc's rules which I think decreases readability of the code or pollutes it.
3. I will continue applying Codenarc to the project packages in separate PR.

> And ... If you're interested in kubernetes at all we've started development on the gradle-kubernetes-plugin which we could also benefit greatly from having these tools.

Sounds interesting. Lets apply Codenarc validations to the current project, create the non-controversial set of rules and apply it to gradle-kubernetes-plugin project.

**Comment by cdancy** [comment]
@MEZk look and sounds good. I remember doing this from scratch on my project `bitbucket-rest` after it was well past the mature point and had loads of files. Took forever to go through and get it done properly so I feel your pain here but highly appreciate you helping this project out for the betterment of all of us.

**Comment by cdancy** [comment]
@MEZk merged and thanks for the PR! Looking forward to the followup work ;)

**Pull request merged**
