### PR TITLE
Cleanup close calls

### PR DESCRIPTION
**Pull request by Sineaggi**
Not sure if this needs a related issue, but there are a few calls to `close()` methods that should no longer be necessary since the groovy 3 try-with-resources changes.

Removes now-unused `closeQuietly()` method.

### CODE REVIEW

**Comment by bmuschko** [comment]
This change would make the plugin incompatible automatically with all Gradle versions that still use Groovy 2. I'd like to avoid making the change if I can for backward-compatibility reasons. I am not sure which version is really the last compatible Gradle version as I am not testing against different Gradle version. It would take far too long to run those tests.

**Comment by Sineaggi** [comment]
With the release of 8.0, the user guide https://bmuschko.github.io/gradle-docker-plugin/current/user-guide/ says
> This plugin requires Gradle >= 7.4.0 to work properly.

and gradle >= 7.0 has a baseline of groovy 3.

**Comment by Sineaggi** [comment]
I've added an alternate commit that uses the `withClosable(Closure)` which is groovy 2 compatible.

**Comment by bmuschko** [comment]
You can only really make a determination about compatibility for the Gradle version used to build the plugin. All other versions can potentially have backward- or forward-compatibility issues if you don't test for it aka running all test cases with the Gradle distribution you are planning to support. That's why the user guide of the plugin makes this statement. Long-term, I would like to change all production source code of the plugin to Java to element the Groovy variable here.

**Comment by bmuschko** [comment]
The CI build is currently failing. I believe this is due to scoping of a method call from a Closure. Honestly, I don't quite see the benefit for making the changes in this PR given that I'd like to keep the code as Java-esque as a possible to easy a transition. Let's close this PR. Thanks again.

**Comment by Sineaggi** [comment]
> Long-term, I would like to change all production source code of the plugin to Java to element the Groovy variable here.
> Honestly, I don't quite see the benefit for making the changes in this PR given that I'd like to keep the code as Java-esque as a possible to easy a transition.

This seems reasonable, in that case we could still merge the first commit as it would be closer to the Java way to auto-close reasource.

**Pull request closed without merging**
