### PR TITLE
Use Colima for Mac build

### PR DESCRIPTION
**Pull request by bmuschko**

### CODE REVIEW

**Comment by bmuschko** [comment]
I though this would work with Docker Java 3.3.0: https://github.com/docker-java/docker-java/pull/2036. I guess not.

**Comment by cdancy** [comment]
@bmuschko what issues did you hit with mac and colima? Someone just recommended this to me the other day and I installed it over docker desktop and it seems to "just work". Haven't tried with the plugin but I know there is talk going on internally here of having users just use this over the more heavy docker-desktop.

**Comment by bmuschko** [comment]
See https://github.com/bmuschko/gradle-docker-plugin/actions/runs/4463239901/jobs/7838303722 and the corresponding build scan: https://scans.gradle.com/s/gkuqail2ngeka/tests/:functionalTest/com.bmuschko.gradle.docker.DockerJavaApplicationPluginFunctionalTest/Can%20create%20image%20and%20start%20container%20for%20Java%20application%20with%20default%20configuration%20and%20configuration%20cache%20enabled?top-execution=1

**Comment by cdancy** [comment]
Oh interesting ... that should be easy enough to solve. Does no one in the community have a few hours to knock this out?!? :)

**Pull request closed without merging**
