### PR TITLE
API cleanup of Dockerfile task

### PR DESCRIPTION
**Pull request by bmuschko**
* Restructure some of the input types for specific instructions so that they become extendible
* Add `chown` parameter to ADD and COPY instruction
* More Javadocs

### CODE REVIEW

**Comment by cdancy** [comment]
The changes here seem to require more typing and verbosity from the user now on top of breaking the existing API. While I'm sure this would be more friendly for IDE's and allow for code completion it could prove to be a pain in the butt.

**Comment by bmuschko** [comment]
> The changes here seem to require more typing and verbosity from the user now on top of breaking the existing API.

Which change exactly? Are you talking about the new `with` builder methods for `File` and `From`? Having constructors with a lot of parameters is an anti-pattern. Just wondering...how would you provide the `chown` parameter?

The breaking change won't be an issue in general. This change will go into a major version change.

**Comment by cdancy** [comment]
@bmuschko take this for example:
```
            task dockerfile(type: Dockerfile) {
                from '$TEST_IMAGE_WITH_TAG'
                addFile('./aaa', 'aaa') // _previous_
                addFile(new Dockerfile.File('./aaa', 'aaa')) _current_
            }
```
The new way to do things is more verbose if I'm not mistaken. And that may be required it just feels a lot more to add on for the user and is not exactly user friendly.

**Comment by bmuschko** [comment]
@cdancy The previous example still works even with this change.

**Comment by bmuschko** [comment]
@cdancy With my previous comment do you still have the same opinion about this change?

**Comment by cdancy** [comment]
@bmuschko +1. LGTM.

**Pull request merged**
